server:
  port: 8082

spring:
  config:
    activate:
      on-profile: "production2"
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: kingsubinkingsubinkingsubinkingsubinkingsubinkingsubinkingsubinkingsubinkingsubinkingsubin
