spring:
  config:
    activate:
      on-profile: "development"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springuser
    password: password
    url: jdbc:mysql://localhost:3306/soob_server?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: kingsubinkingsubinkingsubinkingsubinkingsubinkingsubinkingsubinkingsubinkingsubinkingsubin
