spring:
  profiles:
    group:
      "development": "development, mail"
      "production1": "production1, mail, production-db"
      "production2": "production2, mail, production-db"
management:
  endpoint:
    health:
      show-details: always
